version: "3"

services:
  organization_node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3330:3330"
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      # - ./config:/config
