apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-veramo-agent
  namespace: identi-veramo-agent
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: crypto-veramo-agent
  template:
    metadata:
      labels:
        app: crypto-veramo-agent
    spec:
      containers:
      - name: crypto-veramo-agent
        image: ghcr.io/identi-digital/crypto-veramo-agent:v1.0.10-dev
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: crypto-veramo-agent-pg-pwd
                key: password

          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: crypto-veramo-agent-pg-pwd
                key: SECRET_KEY

          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: POSTGRES_USER

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: POSTGRES_DB

          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: POSTGRES_PORT

          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: POSTGRES_HOST

          - name: SQLALCHEMY_DATABASE_URL
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"

          - name: DOCS_URL
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: DOCS_URL

          - name: REDOC_URL
            valueFrom:
              configMapKeyRef:
                name: crypto-veramo-agent-cm
                key: REDOC_URL

        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
      imagePullSecrets:
        - name: ghcr-io-auth
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: crypto-veramo-agent-service
  namespace: identi-veramo-agent
spec:
  selector:
    app: crypto-veramo-agent
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      name: crypto-veramo-agent
