import dotenv from 'dotenv'
dotenv.config()

export default {
  env: process.env.NODE_ENV || 'test',
  port: process.env.PORT || '3330',
  API_VERSION: process.env.API_VERSION || '1.0.0',
  hash_key: process.env.HASH_KEY || '',
  AWS_JWT_PREFIX: process.env.AWS_JWT_PREFIX || '',
  JWT_HASH_KEY: process.env.JWT_HASH_KEY || '',
  SHARE_VC_HASH_KEY: process.env.SHARE_VC_HASH_KEY || '',
  SHARE_VC_HOST: process.env.SHARE_VC_HOST || '',
  postgresURI: {
    host: process.env.PG_DB_HOST || 'localhost',
    port: parseInt(process.env.PG_DB_PORT?.toString() || '5432'),
    database: process.env.PG_DB_DATABASE || 'testing',
    username: process.env.PG_DB_USERNAME || 'postgres',
    password: process.env.PG_DB_PASSWORD || '123456',
    dialect: process.env.PG_DB_DIALECT || 'postgres',
  },
  CELO_PRIVATE_KEY: process.env.CELO_PRIVATE_KEY || '',
  CELO_NODE_URL: process.env.CELO_NODE_URL || '',
  VERAMO_KMS: process.env.VERAMO_KMS || '',
  DID_PROVIDER: process.env.DID_PROVIDER || '',
  IDENTI_DID: process.env.IDENTI_DID || '',
  IDENTI_DID_KID: process.env.IDENTI_DID_KID || '',
  IDENTI_DID_ALIAS: process.env.IDENTI_DID_ALIAS || '',
  CRYPTO_AGENT_BASE_URL: process.env.CRYPTO_AGENT_BASE_URL || '',
  CRYPTO_AGENT_API_KEY: process.env.CRYPTO_AGENT_API_KEY || '',
  DID_AGENT_BASE_URL: process.env.DID_AGENT_BASE_URL || '',
  DID_AGENT_API_KEY: process.env.DID_AGENT_API_KEY || '',
  USDC_CONTRACT_ADDRESS: process.env.USDC_CONTRACT_ADDRESS || '',
  USDC_ADAPTER_CONTRACT_ADDRESS: process.env.USDC_ADAPTER_CONTRACT_ADDRESS || '',
  CIMMYT_API_KEY: process.env.CIMMYT_API_KEY || '',
}
